### ISSUE TITLE
Display dialog box message when the Game is Tied

### ISSUE THREAD

**Issue by utkarsh006** [utkarsh006/TIC-TAC-TOE#1]

**Comment by binayshaw7777** [comment]
I would like to contribute to this issue! @utkarsh006

**Comment by utkarsh006** [comment]
@binayshaw7777 Start working on the issue. Happy Contributing ✌

**Comment by binayshaw7777** [comment]
I'm really sorry @utkarsh006 . Due to some unavoidable circumstances, I won't be able to contribute to this issue. Could you please remove the assigned role?

**Comment by OmkarGeedh** [comment]
I would like to contribute @utkarsh006

**Comment by utkarsh006** [comment]
@OmkarGeedh Start working on the issue

**Comment by utkarsh006** [comment]
@OmkarGeedh Create a PR till today midnight else issue will be unassigned

**Comment by HawkItzme** [comment]
Hey @utkarsh006 please assign this issue to me.
