### ISSUE TITLE
Add Music in the Game as per Win and Lose 

### ISSUE THREAD

**Issue by utkarsh006** [utkarsh006/TIC-TAC-TOE#4]

**Comment by OmkarGeedh** [comment]
I want to work on this issue.

**Comment by utkarsh006** [comment]
@OmkarGeedh You can work on one issue at a time.

**Comment by HawkItzme** [comment]
Hey @utkarsh006 can you assign me this issue please?

**Comment by HawkItzme** [comment]
Hey, @utkarsh006  should i send you App Video recording here or in the discord server?

**Comment by HawkItzme** [comment]
Hey, please review @utkarsh006  and please tell should I make a PR?

https://user-images.githubusercontent.com/86477458/187302859-12643a96-3564-4659-a436-04de552abf8a.mp4
